version: '3.9'
services:
  backend:
    restart: unless-stopped
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 3000
    deploy:
      resources:
        reservations:
          memory: 0.5G
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/questions"]

  frontend:
    restart: unless-stopped
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_SERVER: https://commit111-backend--3000.prod1.defang.dev/
    ports:
      - mode: ingress
        target: 3000
    deploy:
      resources:
        reservations:
          memory: 1G
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/"]
      